version: '3.7'
services:
  mysql:
    image: library/postgresql:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=db_app
      - POSTGRES_PASSWORD=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
